# Generated by Django 4.1.3 on 2023-02-04 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_name', models.CharField(max_length=20, unique=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.users')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.TextField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
                ('is_importand', models.BooleanField()),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tasks.todo')),
            ],
        ),
    ]
