# Generated by Django 4.1.3 on 2023-02-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_importand',
            field=models.BooleanField(default=False),
        ),
    ]
